import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, AbstractControl } from '@angular/forms';


// dropdown with categories
// select country, with other countries deactivated
// select region, sealand, midjylland, etc.
@Component({
  selector: 'app-search-bar',
  templateUrl: './search-bar.component.html',
  styleUrls: ['./search-bar.component.scss']
})
export class SearchBarComponent implements OnInit {
  searchBar: FormGroup;
  category : AbstractControl;
  country : AbstractControl;
  region : AbstractControl;
  categories: string[];
  countries: Object[];
  regions: string[];

  constructor(private fb: FormBuilder) {
    this.searchBar = fb.group({
      'category': ['', Validators.compose([Validators.required])],
      'country': ['', Validators.compose([Validators.required])],
      'region': ['', Validators.compose([Validators.required])]
    })

    this.category = this.searchBar.controls['category'];
    this.country = this.searchBar.controls['country'];
    this.region = this.searchBar.controls['region'];

    this.categories = [
        'Service Category', 'Mobile', 'Internet', 'TV'
    ];

    this.regions = [
        'Select Region', 'Zealand', 'North Jutland', 'Central Jutland', 'South Jutland'
    ]

    this.countries = [
      { abbreviation: '', name: 'Select Country' },
      // { abbreviation: 'af', name: 'Afghanistan' },
      // { abbreviation: 'ax', name: 'Aland Islands' },
      // { abbreviation: 'al', name: 'Albania' },
      // { abbreviation: 'dz', name: 'Algeria' },
      // { abbreviation: 'as', name: 'American Samoa' },
      // { abbreviation: 'ad', name: 'Andorra' },
      // { abbreviation: 'ao', name: 'Angola' },
      // { abbreviation: 'ai', name: 'Anguilla' },
      // { abbreviation: 'ag', name: 'Antigua' },
      // { abbreviation: 'ar', name: 'Argentina' },
      // { abbreviation: 'am', name: 'Armenia' },
      // { abbreviation: 'aw', name: 'Aruba' },
      // { abbreviation: 'au', name: 'Australia' },
      // { abbreviation: 'at', name: 'Austria' },
      // { abbreviation: 'az', name: 'Azerbaijan' },
      // { abbreviation: 'bs', name: 'Bahamas' },
      // { abbreviation: 'bh', name: 'Bahrain' },
      // { abbreviation: 'bd', name: 'Bangladesh' },
      // { abbreviation: 'bb', name: 'Barbados' },
      // { abbreviation: 'by', name: 'Belarus' },
      // { abbreviation: 'be', name: 'Belgium' },
      // { abbreviation: 'bz', name: 'Belize' },
      // { abbreviation: 'bj', name: 'Benin' },
      // { abbreviation: 'bm', name: 'Bermuda' },
      // { abbreviation: 'bt', name: 'Bhutan' },
      // { abbreviation: 'bo', name: 'Bolivia' },
      // { abbreviation: 'ba', name: 'Bosnia' },
      // { abbreviation: 'bw', name: 'Botswana' },
      // { abbreviation: 'bv', name: 'Bouvet Island' },
      // { abbreviation: 'br', name: 'Brazil' },
      // { abbreviation: 'vg', name: 'British Virgin Islands' },
      // { abbreviation: 'bn', name: 'Brunei' },
      // { abbreviation: 'bg', name: 'Bulgaria' },
      // { abbreviation: 'bf', name: 'Burkina Faso' },
      // { abbreviation: 'mm', name: 'Burma' },
      // { abbreviation: 'bi', name: 'Burundi' },
      // { abbreviation: 'tc', name: 'Caicos Islands' },
      // { abbreviation: 'kh', name: 'Cambodia' },
      // { abbreviation: 'cm', name: 'Cameroon' },
      // { abbreviation: 'ca', name: 'Canada' },
      // { abbreviation: 'cv', name: 'Cape Verde' },
      // { abbreviation: 'ky', name: 'Cayman Islands' },
      // { abbreviation: 'cf', name: 'Central African Republic' },
      // { abbreviation: 'td', name: 'Chad' },
      // { abbreviation: 'cl', name: 'Chile' },
      // { abbreviation: 'cn', name: 'China' },
      // { abbreviation: 'cx', name: 'Christmas Island' },
      // { abbreviation: 'cc', name: 'Cocos Islands' },
      // { abbreviation: 'co', name: 'Colombia' },
      // { abbreviation: 'km', name: 'Comoros' },
      // { abbreviation: 'cg', name: 'Congo Brazzaville' },
      // { abbreviation: 'cd', name: 'Congo' },
      // { abbreviation: 'ck', name: 'Cook Islands' },
      // { abbreviation: 'cr', name: 'Costa Rica' },
      // { abbreviation: 'ci', name: 'Cote Divoire' },
      // { abbreviation: 'hr', name: 'Croatia' },
      // { abbreviation: 'cu', name: 'Cuba' },
      // { abbreviation: 'cy', name: 'Cyprus' },
      // { abbreviation: 'cz', name: 'Czech Republic' },
      { abbreviation: 'dk', name: 'Denmark' },
      // { abbreviation: 'dj', name: 'Djibouti' },
      // { abbreviation: 'dm', name: 'Dominica' },
      // { abbreviation: 'do', name: 'Dominican Republic' },
      // { abbreviation: 'ec', name: 'Ecuador' },
      // { abbreviation: 'eg', name: 'Egypt' },
      // { abbreviation: 'sv', name: 'El Salvador' },
      // { abbreviation: 'gb', name: 'England' },
      // { abbreviation: 'gq', name: 'Equatorial Guinea' },
      // { abbreviation: 'er', name: 'Eritrea' },
      // { abbreviation: 'ee', name: 'Estonia' },
      // { abbreviation: 'et', name: 'Ethiopia' },
      // { abbreviation: 'eu', name: 'European Union' },
      // { abbreviation: 'fk', name: 'Falkland Islands' },
      // { abbreviation: 'fo', name: 'Faroe Islands' },
      // { abbreviation: 'fj', name: 'Fiji' },
      // { abbreviation: 'fi', name: 'Finland' },
      // { abbreviation: 'fr', name: 'France' },
      // { abbreviation: 'gf', name: 'French Guiana' },
      // { abbreviation: 'pf', name: 'French Polynesia' },
      // { abbreviation: 'tf', name: 'French Territories' },
      // { abbreviation: 'ga', name: 'Gabon' },
      // { abbreviation: 'gm', name: 'Gambia' },
      // { abbreviation: 'ge', name: 'Georgia' },
      // { abbreviation: 'de', name: 'Germany' },
      // { abbreviation: 'gh', name: 'Ghana' },
      // { abbreviation: 'gi', name: 'Gibraltar' },
      // { abbreviation: 'gr', name: 'Greece' },
      // { abbreviation: 'gl', name: 'Greenland' },
      // { abbreviation: 'gd', name: 'Grenada' },
      // { abbreviation: 'gp', name: 'Guadeloupe' },
      // { abbreviation: 'gu', name: 'Guam' },
      // { abbreviation: 'gt', name: 'Guatemala' },
      // { abbreviation: 'gw', name: 'Guinea-Bissau' },
      // { abbreviation: 'gn', name: 'Guinea' },
      // { abbreviation: 'gy', name: 'Guyana' },
      // { abbreviation: 'ht', name: 'Haiti' },
      // { abbreviation: 'hm', name: 'Heard Island' },
      // { abbreviation: 'hn', name: 'Honduras' },
      // { abbreviation: 'hk', name: 'Hong Kong' },
      // { abbreviation: 'hu', name: 'Hungary' },
      // { abbreviation: 'is', name: 'Iceland' },
      // { abbreviation: 'in', name: 'India' },
      // { abbreviation: 'io', name: 'Indian Ocean Territory' },
      // { abbreviation: 'id', name: 'Indonesia' },
      // { abbreviation: 'ir', name: 'Iran' },
      // { abbreviation: 'iq', name: 'Iraq' },
      // { abbreviation: 'ie', name: 'Ireland' },
      // { abbreviation: 'il', name: 'Israel' },
      // { abbreviation: 'it', name: 'Italy' },
      // { abbreviation: 'jm', name: 'Jamaica' },
      // { abbreviation: 'jp', name: 'Japan' },
      // { abbreviation: 'jo', name: 'Jordan' },
      // { abbreviation: 'kz', name: 'Kazakhstan' },
      // { abbreviation: 'ke', name: 'Kenya' },
      // { abbreviation: 'ki', name: 'Kiribati' },
      // { abbreviation: 'kw', name: 'Kuwait' },
      // { abbreviation: 'kg', name: 'Kyrgyzstan' },
      // { abbreviation: 'la', name: 'Laos' },
      // { abbreviation: 'lv', name: 'Latvia' },
      // { abbreviation: 'lb', name: 'Lebanon' },
      // { abbreviation: 'ls', name: 'Lesotho' },
      // { abbreviation: 'lr', name: 'Liberia' },
      // { abbreviation: 'ly', name: 'Libya' },
      // { abbreviation: 'li', name: 'Liechtenstein' },
      // { abbreviation: 'lt', name: 'Lithuania' },
      // { abbreviation: 'lu', name: 'Luxembourg' },
      // { abbreviation: 'mo', name: 'Macau' },
      // { abbreviation: 'mk', name: 'Macedonia' },
      // { abbreviation: 'mg', name: 'Madagascar' },
      // { abbreviation: 'mw', name: 'Malawi' },
      // { abbreviation: 'my', name: 'Malaysia' },
      // { abbreviation: 'mv', name: 'Maldives' },
      // { abbreviation: 'ml', name: 'Mali' },
      // { abbreviation: 'mt', name: 'Malta' },
      // { abbreviation: 'mh', name: 'Marshall Islands' },
      // { abbreviation: 'mq', name: 'Martinique' },
      // { abbreviation: 'mr', name: 'Mauritania' },
      // { abbreviation: 'mu', name: 'Mauritius' },
      // { abbreviation: 'yt', name: 'Mayotte' },
      // { abbreviation: 'mx', name: 'Mexico' },
      // { abbreviation: 'fm', name: 'Micronesia' },
      // { abbreviation: 'md', name: 'Moldova' },
      // { abbreviation: 'mc', name: 'Monaco' },
      // { abbreviation: 'mn', name: 'Mongolia' },
      // { abbreviation: 'me', name: 'Montenegro' },
      // { abbreviation: 'ms', name: 'Montserrat' },
      // { abbreviation: 'ma', name: 'Morocco' },
      // { abbreviation: 'mz', name: 'Mozambique' },
      // { abbreviation: 'na', name: 'Namibia' },
      // { abbreviation: 'nr', name: 'Nauru' },
      // { abbreviation: 'np', name: 'Nepal' },
      // { abbreviation: 'an', name: 'Netherlands Antilles' },
      // { abbreviation: 'nl', name: 'Netherlands' },
      // { abbreviation: 'nc', name: 'New Caledonia' },
      // { abbreviation: 'pg', name: 'New Guinea' },
      // { abbreviation: 'nz', name: 'New Zealand' },
      // { abbreviation: 'ni', name: 'Nicaragua' },
      // { abbreviation: 'ne', name: 'Niger' },
      // { abbreviation: 'ng', name: 'Nigeria' },
      // { abbreviation: 'nu', name: 'Niue' },
      // { abbreviation: 'nf', name: 'Norfolk Island' },
      // { abbreviation: 'kp', name: 'North Korea' },
      // { abbreviation: 'mp', name: 'Northern Mariana Islands' },
      // { abbreviation: 'no', name: 'Norway' },
      // { abbreviation: 'om', name: 'Oman' },
      // { abbreviation: 'pk', name: 'Pakistan' },
      // { abbreviation: 'pw', name: 'Palau' },
      // { abbreviation: 'ps', name: 'Palestine' },
      // { abbreviation: 'pa', name: 'Panama' },
      // { abbreviation: 'py', name: 'Paraguay' },
      // { abbreviation: 'pe', name: 'Peru' },
      // { abbreviation: 'ph', name: 'Philippines' },
      // { abbreviation: 'pn', name: 'Pitcairn Islands' },
      // { abbreviation: 'pl', name: 'Poland' },
      // { abbreviation: 'pt', name: 'Portugal' },
      // { abbreviation: 'pr', name: 'Puerto Rico' },
      // { abbreviation: 'qa', name: 'Qatar' },
      // { abbreviation: 're', name: 'Reunion' },
      // { abbreviation: 'ro', name: 'Romania' },
      // { abbreviation: 'ru', name: 'Russia' },
      // { abbreviation: 'rw', name: 'Rwanda' },
      // { abbreviation: 'sh', name: 'Saint Helena' },
      // { abbreviation: 'kn', name: 'Saint Kitts and Nevis' },
      // { abbreviation: 'lc', name: 'Saint Lucia' },
      // { abbreviation: 'pm', name: 'Saint Pierre' },
      // { abbreviation: 'vc', name: 'Saint Vincent' },
      // { abbreviation: 'ws', name: 'Samoa' },
      // { abbreviation: 'sm', name: 'San Marino' },
      // { abbreviation: 'gs', name: 'Sandwich Islands' },
      // { abbreviation: 'st', name: 'Sao Tome' },
      // { abbreviation: 'sa', name: 'Saudi Arabia' },
      // { abbreviation: 'sn', name: 'Senegal' },
      // { abbreviation: 'cs', name: 'Serbia' },
      // { abbreviation: 'rs', name: 'Serbia' },
      // { abbreviation: 'sc', name: 'Seychelles' },
      // { abbreviation: 'sl', name: 'Sierra Leone' },
      // { abbreviation: 'sg', name: 'Singapore' },
      // { abbreviation: 'sk', name: 'Slovakia' },
      // { abbreviation: 'si', name: 'Slovenia' },
      // { abbreviation: 'sb', name: 'Solomon Islands' },
      // { abbreviation: 'so', name: 'Somalia' },
      // { abbreviation: 'za', name: 'South Africa' },
      // { abbreviation: 'kr', name: 'South Korea' },
      // { abbreviation: 'es', name: 'Spain' },
      // { abbreviation: 'lk', name: 'Sri Lanka' },
      // { abbreviation: 'sd', name: 'Sudan' },
      // { abbreviation: 'sr', name: 'Suriname' },
      // { abbreviation: 'sj', name: 'Svalbard' },
      // { abbreviation: 'sz', name: 'Swaziland' },
      // { abbreviation: 'se', name: 'Sweden' },
      // { abbreviation: 'ch', name: 'Switzerland' },
      // { abbreviation: 'sy', name: 'Syria' },
      // { abbreviation: 'tw', name: 'Taiwan' },
      // { abbreviation: 'tj', name: 'Tajikistan' },
      // { abbreviation: 'tz', name: 'Tanzania' },
      // { abbreviation: 'th', name: 'Thailand' },
      // { abbreviation: 'tl', name: 'Timorleste' },
      // { abbreviation: 'tg', name: 'Togo' },
      // { abbreviation: 'tk', name: 'Tokelau' },
      // { abbreviation: 'to', name: 'Tonga' },
      // { abbreviation: 'tt', name: 'Trinidad' },
      // { abbreviation: 'tn', name: 'Tunisia' },
      // { abbreviation: 'tr', name: 'Turkey' },
      // { abbreviation: 'tm', name: 'Turkmenistan' },
      // { abbreviation: 'tv', name: 'Tuvalu' },
      // { abbreviation: 'ug', name: 'Uganda' },
      // { abbreviation: 'ua', name: 'Ukraine' },
      // { abbreviation: 'ae', name: 'United Arab Emirates' },
      // { abbreviation: 'us', name: 'United States' },
      // { abbreviation: 'uy', name: 'Uruguay' },
      // { abbreviation: 'um', name: 'Us Minor Islands' },
      // { abbreviation: 'vi', name: 'Us Virgin Islands' },
      // { abbreviation: 'uz', name: 'Uzbekistan' },
      // { abbreviation: 'vu', name: 'Vanuatu' },
      // { abbreviation: 'va', name: 'Vatican City' },
      // { abbreviation: 've', name: 'Venezuela' },
      // { abbreviation: 'vn', name: 'Vietnam' },
      // { abbreviation: 'wf', name: 'Wallis and Futuna' },
      // { abbreviation: 'eh', name: 'Western Sahara' },
      // { abbreviation: 'ye', name: 'Yemen' },
      // { abbreviation: 'zm', name: 'Zambia' },
      // { abbreviation: 'zw', name: 'Zimbabwe' }
    ];
  }

  ngOnInit() { }

  onSubmit(form: any): void {
    if (form.name != null) {
      console.log('You submitted the form', form);
    }

    this.searchBar.reset();
  }

}
